language: java
jdk:
- oraclejdk8
sudo: false
install: true
script:
- mvn package
after_success:
- mkdir codedeploy
- zip -r final.zip target/project-1.0.0-BUILD-SNAPSHOT.war appspec.yml restartTomcat.sh
- ls -al
- mv final.zip codedeploy/
- ls -al
- pwd
- cd codedeploy
- ls -al
- pwd
before_deploy:
- cd ..
- pwd

deploy:
  - provider: s3
    access_key_id: AKIAJEPUN3YQCGSDQBMQ
    secret_access_key:
     secure: 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
    local_dir: codedeploy
    bucket: code-deploy.neu-csye6225-spring2017-team-3.com
    region: us-west-1
    skip_cleanup: true
  - provider: codedeploy
    access_key_id: AKIAJEPUN3YQCGSDQBMQ
    bucket: code-deploy.neu-csye6225-spring2017-team-3.com
    key: final.zip
    bundle_type: zip
    application: csye6225-3
    deployment_group: csye6225-3
    region: us-west-1
    wait-until-deployed: true
    secret_access_key:
     secure: xPsyE/w3EAPSKDudTbH0mag79jNj4tlQA5FcgaI7
notifications:
  email:
    recipients:
    - babbar.p@husky.neu.edu
