language: java
jdk:
- oraclejdk8
sudo: false
install: true
script:
- mvn package
after_success:
- mkdir codedeploy
- zip -r final.zip target/project-1.0.0-BUILD-SNAPSHOT.war appspec.yml restartTomcat.sh
- ls -al
- mv final.zip codedeploy/
- ls -al
- pwd
- cd codedeploy
- ls -al
- pwd
before_deploy:
- cd ..
- pwd
deploy:
  matrix:
  - provider: s3
    access_key_id: AKIAJEPUN3YQCGSDQBMQ
    secret_access_key:
      secure: cEVUEYgdwl611H5C7Lkow11pD/+Ie3YUyD4/lrb1kGuXUOaatS/bimq/cSw40cGy0XvfRlUJValWfwbTUDPyCgOXfjRRHOhdbcS3/9wkljMvUW/BkL7E7NAV/06r38nkaF8GwOE6ToNc4JvUcea3yc8+szCtjrfUhNHNL2fI1okLHA1CsCxaNgkI1wHKx5fLUkF2ni6oIpUIHpwnWdRxoaSBW6uXFDBbPCPareHBhTdi69Q6jt2uQYJC1myENJMZvDOSCKvOXRSjSrOq3v9gm7OUVBr9HHE6EWwMAI5+i/ThFfGPyIK+BHDWSEJEg+OkTRNqWlXTRICr7pA19JtawJcVOS7MUtKCOShagpLIwQbVCz5TeL5rsXzfdXiaE5JhM+t/3QUKsCDONLUuuyBhepWL93kg5mkBkXKbb9r4ZrijK3l8ul2kiwz30XseDnGvPo+01aODCSu+eIzX4ZYuxbbWFw5kR586QYiT7UxKejvgCLp+W3mQHtN1aOx2nie4azh5iBzMmiszvMXM82iiO43Ul7WnSMpNz3F1XfS4URQiqhKHyinf2mfeee/FSDgywkNuEk+VLJsW1cpA/+dE+qmWsT9TfP2/sTN0yMO0uad9y15gQfn/4r06CL1Xi8wOWjMzSzZVg8lyLOrNfL2jNTfZLCxiLugPSdam7xya53g=

    local_dir: codedeploy
    bucket: code-deploy.neu-csye6225-spring2017-team-3.com
    region: us-west-1
    skip_cleanup: true
  - provider: codedeploy
    access_key_id: AKIAJEPUN3YQCGSDQBMQ
    bucket: code-deploy.neu-csye6225-spring2017-team-3.com
    key: final.zip
    bundle_type: zip
    application: csye6225-3
    deployment_group: csye6225-3
    region: us-west-1
    wait-until-deployed: true
    secret_access_key:
      secure: xPsyE/w3EAPSKDudTbH0mag79jNj4tlQA5FcgaI7
  secret_access_key:
    secure: cEVUEYgdwl611H5C7Lkow11pD/+Ie3YUyD4/lrb1kGuXUOaatS/bimq/cSw40cGy0XvfRlUJValWfwbTUDPyCgOXfjRRHOhdbcS3/9wkljMvUW/BkL7E7NAV/06r38nkaF8GwOE6ToNc4JvUcea3yc8+szCtjrfUhNHNL2fI1okLHA1CsCxaNgkI1wHKx5fLUkF2ni6oIpUIHpwnWdRxoaSBW6uXFDBbPCPareHBhTdi69Q6jt2uQYJC1myENJMZvDOSCKvOXRSjSrOq3v9gm7OUVBr9HHE6EWwMAI5+i/ThFfGPyIK+BHDWSEJEg+OkTRNqWlXTRICr7pA19JtawJcVOS7MUtKCOShagpLIwQbVCz5TeL5rsXzfdXiaE5JhM+t/3QUKsCDONLUuuyBhepWL93kg5mkBkXKbb9r4ZrijK3l8ul2kiwz30XseDnGvPo+01aODCSu+eIzX4ZYuxbbWFw5kR586QYiT7UxKejvgCLp+W3mQHtN1aOx2nie4azh5iBzMmiszvMXM82iiO43Ul7WnSMpNz3F1XfS4URQiqhKHyinf2mfeee/FSDgywkNuEk+VLJsW1cpA/+dE+qmWsT9TfP2/sTN0yMO0uad9y15gQfn/4r06CL1Xi8wOWjMzSzZVg8lyLOrNfL2jNTfZLCxiLugPSdam7xya53g=
notifications:
  email:
    recipients:
    - babbar.p@husky.neu.edu
