version: 0.0
os: linux

files:
  - source: ./appspec.yml
    destination: /home/ubuntu
  - source: ./restartTomcat.sh
    destination: /home/ubuntu
  - source: ./target/project-1.0.0-BUILD-SNAPSHOT.war
    destination: /var/lib/tomcat7/webapps

#permissions:
#  - object: /var/lib/tomcat7/webapps
#      pattern: "**"
#      owner: tomcat7
#      group: tomcat7
#      mode: 755
#      type:
#        - directory
#  - object: /home/ubuntu
#      pattern: "*.sh"
#      owner: ubuntu
#      mode: 755
#      type:
#        - file

hooks:
  AfterInstall:
   - location: ./restartTomcat.sh
     timeout: 180
     runas: ubuntu
